insert into student (name, address) values ('Greer', 'Gujarat');
insert into student (name, address) values ('Davina', 'Andhra Pradesh');
insert into student (name, address) values ('Lisetta', 'Karnataka');
insert into student (name, address) values ('Brew', 'Haryana');
insert into student (name, address) values ('Geneva', 'Karnataka');
insert into student (name, address) values ('Bidget', 'Meghalaya');
insert into student (name, address) values ('Pasquale', 'Sikkim');
insert into student (name, address) values ('Berne', 'Odisha');
insert into student (name, address) values ('Dorene', 'West Bengal');
insert into student (name, address) values ('Nelle', 'Himachal Pradesh');
insert into student (name, address) values ('Lucy', 'Meghalaya');
insert into student (name, address) values ('Alexandra', 'Manipur');
insert into student (name, address) values ('Sutherlan', 'Jharkhand');
insert into student (name, address) values ('Chrissy', 'Madhya Pradesh');
insert into student (name, address) values ('Thornie', 'Arunachal Pradesh');
insert into student (name, address) values ('Sandye', 'Bihar');
insert into student (name, address) values ('Pamella', 'Assam');
insert into student (name, address) values ('Naomi', 'Assam');
insert into student (name, address) values ('Nealson', 'Telangana');
insert into student (name, address) values ('Stevana', 'Gujarat');
insert into student (name, address) values ('Pascal', 'West Bengal');
insert into student (name, address) values ('Penni', 'Andhra Pradesh');
insert into student (name, address) values ('Arlen', 'Tamil Nadu');
insert into student (name, address) values ('Alaine', 'Gujarat');
insert into student (name, address) values ('Angel', 'Andhra Pradesh');
insert into student (name, address) values ('Erin', 'Manipur');
insert into student (name, address) values ('Eward', 'Maharashtra');
insert into student (name, address) values ('Carny', 'Rajasthan');
insert into student (name, address) values ('Paul', 'Tripura');
insert into student (name, address) values ('Nolan', 'Rajasthan');
insert into student (name, address) values ('Lindsy', 'Uttarakhand');
insert into student (name, address) values ('Eolanda', 'West Bengal');
insert into student (name, address) values ('Clare', 'Mizoram');
insert into student (name, address) values ('Nollie', 'West Bengal');
insert into student (name, address) values ('Nari', 'Chhattisgarh');
insert into student (name, address) values ('Serene', 'Chhattisgarh');
insert into student (name, address) values ('Christean', 'Maharashtra');
insert into student (name, address) values ('Myrvyn', 'Meghalaya');
insert into student (name, address) values ('La verne', 'Uttarakhand');
insert into student (name, address) values ('Ros', 'Telangana');
insert into student (name, address) values ('Ailsun', 'Assam');
insert into student (name, address) values ('Herschel', 'Arunachal Pradesh');
insert into student (name, address) values ('Rennie', 'Odisha');
insert into student (name, address) values ('Field', 'Rajasthan');
insert into student (name, address) values ('Shay', 'Rajasthan');
insert into student (name, address) values ('Elisabet', 'Assam');
insert into student (name, address) values ('Roarke', 'Haryana');
insert into student (name, address) values ('Anatola', 'Tamil Nadu');
insert into student (name, address) values ('Deny', 'Bihar');
insert into student (name, address) values ('Kalila', 'Meghalaya');
